services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallets
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: postgres:16
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=wallets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password